nombre = "matias"
print(nombre)
print("")
print("Contiene a",'a' in nombre)
print("Contiene e",'e' in nombre)
print("Contiene i",'i' in nombre)
print("Contiene o",'o' in nombre)
print("Contiene u",'u' in nombre)
nombre2 = "augusto"
print("")
print(nombre2)
print("")
print("Contiene a",'a' in nombre2)
print("Contiene e",'e' in nombre2)
print("Contiene i",'i' in nombre2)
print("Contiene o",'o' in nombre2)
print("Contiene u",'u' in nombre2)
